import 'package:flutter/material.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import '../../../core/constants/api_constants.dart';

class TrainingPlanScreen extends StatefulWidget {
  final String goal;
  const TrainingPlanScreen({super.key, required this.goal});

  @override
  State<TrainingPlanScreen> createState() => _TrainingPlanScreenState();
}

class _TrainingPlanScreenState extends State<TrainingPlanScreen> {
  bool _isLoading = true;
  String _planMarkdown = '';
  String _errorMessage = '';

  @override
  void initState() {
    super.initState();
    _fetchTrainingPlan();
  }

  Future<void> _fetchTrainingPlan() async {
    try {
      final encodedGoal = Uri.encodeComponent(widget.goal);
      final url = Uri.parse('${ApiConstants.baseUrl}/training/plan?goal=$encodedGoal');
      final response = await http.get(url);

      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        setState(() {
          _planMarkdown = data['plan'] ?? 'No plan received.';
          _isLoading = false;
        });
      } else {
        setState(() {
          _errorMessage = 'Failed to load plan: ${response.statusCode}';
          _isLoading = false;
        });
      }
    } catch (e) {
      setState(() {
        _errorMessage = 'Network error: $e';
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF121212),
      appBar: AppBar(
        title: const Text('AI Training Plan', style: TextStyle(fontFamily: 'Outfit', fontWeight: FontWeight.bold)),
        backgroundColor: Colors.transparent,
        elevation: 0,
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(24.0),
          child: _buildContent(),
        ),
      ),
    );
  }

  Widget _buildContent() {
    if (_isLoading) {
      return const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(color: Color(0xFFFC4C02)),
            SizedBox(height: 16),
            Text('Analyzing history & generating plan...', style: TextStyle(color: Colors.grey)),
          ],
        ),
      );
    }

    if (_errorMessage.isNotEmpty) {
      return Center(
        child: Text(_errorMessage, style: const TextStyle(color: Colors.red)),
      );
    }

    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Container(
            padding: const EdgeInsets.all(20),
            decoration: BoxDecoration(
              color: Colors.grey[900],
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: const Color(0xFFFC4C02).withOpacity(0.3)),
            ),
            child: Row(
              children: [
                const Icon(Icons.psychology, color: Color(0xFFFC4C02), size: 32),
                const SizedBox(width: 16),
                const Expanded(
                  child: Text(
                    'Generated by Gemini based on your recent Strava performance.',
                    style: TextStyle(color: Colors.white70, fontSize: 14),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),
          MarkdownBody(
            data: _planMarkdown,
            styleSheet: MarkdownStyleSheet(
              h1: const TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold),
              h2: const TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
              h3: const TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.bold),
              p: const TextStyle(color: Colors.white70, fontSize: 16, height: 1.5),
              listBullet: const TextStyle(color: Color(0xFFFC4C02)),
            ),
          ),
        ],
      ),
    );
  }
}
